### PR TITLE
move-definition-to-declaration transformation learned to move struct, class, union and variable definitions

### PR DESCRIPTION
**Pull request by strimo378**

### CODE REVIEW

**Comment by marxin** [comment]
Thank you for your effort!

**Comment by marxin** [comment]
Timo, please let me know how much stuff you have in your queue ;) I would like to make a release once you're done.

**Comment by strimo378** [comment]
I only have one minor improvement in my queue and that is not yet finished. I don't know when I will finish it. From my side there is nothing against a release.

**Comment by marxin** [comment]
Great, then I'm going to do it next week after some testing. Have a nice weekend!

**Comment by strimo378** [comment]
Thx you too!

**Pull request merged**
