### PR TITLE
fix deprecation warnings

### PR DESCRIPTION
**Pull request by oltolm**
I fixed the Clang deprecation warnings.

### CODE REVIEW

**Comment by marxin** [comment]
Hey! I welcome the change, though, we would need to support the older LLVM releases. Can you please come up with a conditional code based on `LLVM_VERSION_MAJOR`?

**Comment by oltolm** [comment]
done

**Comment by marxin** [comment]
Great, can you also exclude now `SUPPORTS_DEPRECATED_DECLARATIONS` (and `-Wno-error=deprecated-declarations` compiler option), please?

**Comment by oltolm** [comment]
> Great, can you also exclude now `SUPPORTS_DEPRECATED_DECLARATIONS` (and `-Wno-error=deprecated-declarations` compiler option), please?

I don't understand.

**Comment by marxin** [comment]
I've just removed that in 857e7113263ed998c8e6d0727ddc32d4b16dd277.
Anyway, thanks for your submission!

**Pull request merged**
