### PR TITLE
LLVM12 support

### PR DESCRIPTION
**Pull request by nickdesaulniers**
see commit messages for references to llvm sha's for breaking changes.

### CODE REVIEW

**Comment by marxin** [comment]
Thank you for the pull request.

Apparently it breaks build with LLVM 9:
```
/usr/src/cvise/clang_delta/RewriteUtils.cpp: In member function 'std::__cxx11::string RewriteUtils::getStmtIndentString(clang::Stmt*, clang::SourceManager*)':
/usr/src/cvise/clang_delta/RewriteUtils.cpp:740:72: error: invalid initialization of reference of type 'const clang::SrcMgr::ContentCache&' from expression of type 'const clang::SrcMgr::ContentCache*'
       Content = SrcManager->getSLocEntry(FID).getFile().getContentCache();
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

Can you please make the change conditional so that we can preserve the support for LLVM9?

**Comment by nickdesaulniers** [comment]
Yeah, sounds good. Is there a preprocessor define to check against?

**Comment by marxin** [comment]
I think `llvm-config.h` provides what you need:

```
/* Major version of the LLVM API */
#define LLVM_VERSION_MAJOR 11

/* Minor version of the LLVM API */
#define LLVM_VERSION_MINOR 0

/* Patch version of the LLVM API */
#define LLVM_VERSION_PATCH 0
```

**Comment by marxin** [comment]
And please rebase it on top of the master, I made some squashing.

**Comment by marxin** [comment]
I've finished your effort on the master, can you please test the current master?

**Pull request closed without merging**
